module kernel_external
!---------------------------------------------
!--own (auto-generated by kernels.py)
!---------------------------------------------
  implicit none

  public :: kf, kdf, kddf, knorm, krad

  private

    real, parameter :: pi = 4.*atan(1.)
    real :: knorm(3) = (/ 1./(-22./975. + 48.*atan(5.)/125.),1./(-2.*pi*(-11.*atan(5.)/375. + 37.*log(26.)/3750.) + 2.*pi*(14./975. + 37.*log(26.)/3750. + 11.*atan(5.)/375.)),1./(-4.*pi*(-119.*atan(5.)/9375. + 4.*log(26.)/625.) + 4.*pi*(119.*atan(5.)/9375. + 4.*log(26.)/625. + 1568./73125.)) /)
    real :: krad = 2.0
 contains

  subroutine kf(r, h, f)
    real, intent(in)  :: r, h
    real, intent(out) :: f
    real              :: q

    q = r / h
    if (q < 0.0) then
      print *, 'f: something went wrong, q =', q
      stop
    else
      f  = -q**2/52. + q*atan(5.*q - 5.)/5. - q*atan(5.)/5. + q/13. - log(25.*q**2 - 50.*q + 26.)/50. - atan(5.*q - 5.)/5. - 1./13. + log(26.)/50. + atan(5.)/5.
    end if
  end subroutine kf

  subroutine kdf(r, h, df)
    real, intent(in)  :: r, h
    real, intent(out) :: df
    real              :: q

    q = r / h
    if (q < 0.0) then
      print *, 'df: something went wrong, q =', q
      stop
    else
      df  = -q/26. + atan(5.*q - 5.)/5. - atan(5.)/5. + 1./13.
    end if
  end subroutine kdf

  subroutine kddf(r, h, ddf)
    real, intent(in)  :: r, h
    real, intent(out) :: ddf
    real              :: q

    q = r / h
    if (q < 0.0) then
      print *, 'ddf: something went wrong, q =', q
      stop
    else
      ddf  = 25.0*(-(q - 1.0)**2 + 1)/(650.0*(q - 1.0)**2 + 26.0)
    end if
  end subroutine kddf
end module kernel_external
